// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#pragma once
#include "behaviac/agent/agent.h"

// -------------------
// Customized enums
// -------------------

enum ETest
{
	EA,

	EB,

	EC,
};

// -------------------
// Customized structs
// -------------------

struct StructTest
{
	bool a;

DECLARE_BEHAVIAC_STRUCT(StructTest);
};

DECLARE_BEHAVIAC_ENUM(ETest, ETest);

SPECIALIZE_TYPE_HANDLER(behaviac::vector<StructTest>, BasicTypeHandler< behaviac::vector<StructTest> >);
