//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginBehaviac.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginBehaviac.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive action.
        /// </summary>
        internal static string ActionDesc {
            get {
                return ResourceManager.GetString("ActionDesc", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap alwaysFailure_ico {
            get {
                object obj = ResourceManager.GetObject("alwaysFailure_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap alwaysSuccess_ico {
            get {
                object obj = ResourceManager.GetObject("alwaysSuccess_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true if all children are true.
        /// </summary>
        internal static string AndDesc {
            get {
                return ResourceManager.GetString("AndDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And and Or are only valid for bool!.
        /// </summary>
        internal static string AndOrOnlyValidForBool {
            get {
                return ResourceManager.GetString("AndOrOnlyValidForBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        internal static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assign the right to the left.
        /// </summary>
        internal static string AssignmentDesc {
            get {
                return ResourceManager.GetString("AssignmentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string AttributeDesc {
            get {
                return ResourceManager.GetString("AttributeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string BehaviorDomain {
            get {
                return ResourceManager.GetString("BehaviorDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag to indicate the type, purpose, etc..
        /// </summary>
        internal static string BehaviorDomainDesc {
            get {
                return ResourceManager.GetString("BehaviorDomainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the impulse blocks the execution and waits for all the events.
        /// </summary>
        internal static string BlockedDesc {
            get {
                return ResourceManager.GetString("BlockedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildFinishPolicy.
        /// </summary>
        internal static string ChildFinishPolicy {
            get {
                return ResourceManager.GetString("ChildFinishPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how to continue if a child node finishes..
        /// </summary>
        internal static string ChildFinishPolicyDesc {
            get {
                return ResourceManager.GetString("ChildFinishPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareGetter.
        /// </summary>
        internal static string CompareGetter {
            get {
                return ResourceManager.GetString("CompareGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call a getter and compare its return value to the right operand.
        /// </summary>
        internal static string CompareGetterDesc {
            get {
                return ResourceManager.GetString("CompareGetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        internal static string Compute {
            get {
                return ResourceManager.GetString("Compute", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap compute_ico {
            get {
                object obj = ResourceManager.GetObject("compute_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the result of Operand1 and Operand2 and assign it to the Left Operand.
        /// </summary>
        internal static string ComputeDesc {
            get {
                return ResourceManager.GetString("ComputeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condition is usually represented by the agent&apos;s properties, pars, etc..
        /// </summary>
        internal static string ConditionDesc {
            get {
                return ResourceManager.GetString("ConditionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionGetter.
        /// </summary>
        internal static string ConditionGetter {
            get {
                return ResourceManager.GetString("ConditionGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call a getter function and compare the return value to the right operand.
        /// </summary>
        internal static string ConditionGetterDesc {
            get {
                return ResourceManager.GetString("ConditionGetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlwaysFailure.
        /// </summary>
        internal static string DecoratorAlwaysFailure {
            get {
                return ResourceManager.GetString("DecoratorAlwaysFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it always returns failure no matter what result the child returns.
        /// </summary>
        internal static string DecoratorAlwaysFailureDesc {
            get {
                return ResourceManager.GetString("DecoratorAlwaysFailureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlwaysRunning.
        /// </summary>
        internal static string DecoratorAlwaysRunning {
            get {
                return ResourceManager.GetString("DecoratorAlwaysRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it always returns running no matter what result the child returns.
        /// </summary>
        internal static string DecoratorAlwaysRunningDesc {
            get {
                return ResourceManager.GetString("DecoratorAlwaysRunningDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlwaysSuccess.
        /// </summary>
        internal static string DecoratorAlwaysSuccess {
            get {
                return ResourceManager.GetString("DecoratorAlwaysSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it always returns success no matter what result the child returns.
        /// </summary>
        internal static string DecoratorAlwaysSuccessDesc {
            get {
                return ResourceManager.GetString("DecoratorAlwaysSuccessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountLimit.
        /// </summary>
        internal static string DecoratorCountLimit {
            get {
                return ResourceManager.GetString("DecoratorCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to limit the count of the exucution.
        /// </summary>
        internal static string DecoratorCountLimitDesc {
            get {
                return ResourceManager.GetString("DecoratorCountLimitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string DecoratorDelay {
            get {
                return ResourceManager.GetString("DecoratorDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string DecoratorDelayDesc {
            get {
                return ResourceManager.GetString("DecoratorDelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailureAfter.
        /// </summary>
        internal static string DecoratorFailureAfter {
            get {
                return ResourceManager.GetString("DecoratorFailureAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failue After the specified count.
        /// </summary>
        internal static string DecoratorFailureAfterDesc {
            get {
                return ResourceManager.GetString("DecoratorFailureAfterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailureUntil.
        /// </summary>
        internal static string DecoratorFailureUntil {
            get {
                return ResourceManager.GetString("DecoratorFailureUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure until the specified count.
        /// </summary>
        internal static string DecoratorFailureUntilDesc {
            get {
                return ResourceManager.GetString("DecoratorFailureUntilDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string DecoratorFrames {
            get {
                return ResourceManager.GetString("DecoratorFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This decorator calls its child within the specified Frames..
        /// </summary>
        internal static string DecoratorFramesDesc {
            get {
                return ResourceManager.GetString("DecoratorFramesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string DecoratorLog {
            get {
                return ResourceManager.GetString("DecoratorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string DecoratorLogDesc {
            get {
                return ResourceManager.GetString("DecoratorLogDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Message.
        /// </summary>
        internal static string DecoratorLogMessage {
            get {
                return ResourceManager.GetString("DecoratorLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log message.
        /// </summary>
        internal static string DecoratorLogMessageDesc {
            get {
                return ResourceManager.GetString("DecoratorLogMessageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        internal static string DecoratorLoop {
            get {
                return ResourceManager.GetString("DecoratorLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string DecoratorLoopCount {
            get {
                return ResourceManager.GetString("DecoratorLoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how often the child will be called. If the child fails, the loop is aborted and fails..
        /// </summary>
        internal static string DecoratorLoopCountDesc {
            get {
                return ResourceManager.GetString("DecoratorLoopCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This decorator calls its child n times. -1 is for endless..
        /// </summary>
        internal static string DecoratorLoopDesc {
            get {
                return ResourceManager.GetString("DecoratorLoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoopUntil.
        /// </summary>
        internal static string DecoratorLoopUntil {
            get {
                return ResourceManager.GetString("DecoratorLoopUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loop until the child returns success/failure or loop for the specified count..
        /// </summary>
        internal static string DecoratorLoopUntilDesc {
            get {
                return ResourceManager.GetString("DecoratorLoopUntilDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        internal static string DecoratorNot {
            get {
                return ResourceManager.GetString("DecoratorNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This decorator inverts the return value of the attached node. If the attached node fails, it will appear as it has succedded and vice versa..
        /// </summary>
        internal static string DecoratorNotDesc {
            get {
                return ResourceManager.GetString("DecoratorNotDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessAfter.
        /// </summary>
        internal static string DecoratorSuccessAfter {
            get {
                return ResourceManager.GetString("DecoratorSuccessAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success After the specified count.
        /// </summary>
        internal static string DecoratorSuccessAfterDesc {
            get {
                return ResourceManager.GetString("DecoratorSuccessAfterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessUntil.
        /// </summary>
        internal static string DecoratorSuccessUntil {
            get {
                return ResourceManager.GetString("DecoratorSuccessUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed until the specified count.
        /// </summary>
        internal static string DecoratorSuccessUntilDesc {
            get {
                return ResourceManager.GetString("DecoratorSuccessUntilDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string DecoratorTime {
            get {
                return ResourceManager.GetString("DecoratorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This decorator calls its child within the specified time(milliseconds)..
        /// </summary>
        internal static string DecoratorTimeDesc {
            get {
                return ResourceManager.GetString("DecoratorTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        internal static string DecoratorUntil {
            get {
                return ResourceManager.GetString("DecoratorUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by default, the decorator loops until the child returns success. if &apos;until&apos; is false, the decorator loops until the child returns failure..
        /// </summary>
        internal static string DecoratorUntilDesc {
            get {
                return ResourceManager.GetString("DecoratorUntilDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        internal static string DecoratorWait {
            get {
                return ResourceManager.GetString("DecoratorWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will wait for a given time to execute the child.
        /// </summary>
        internal static string DecoratorWaitDesc {
            get {
                return ResourceManager.GetString("DecoratorWaitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string DecoratorWeight {
            get {
                return ResourceManager.GetString("DecoratorWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string DecoratorWeightDesc {
            get {
                return ResourceManager.GetString("DecoratorWeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor.
        /// </summary>
        internal static string Descriptor {
            get {
                return ResourceManager.GetString("Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptor.
        /// </summary>
        internal static string DescriptorDesc {
            get {
                return ResourceManager.GetString("DescriptorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptors.
        /// </summary>
        internal static string Descriptors {
            get {
                return ResourceManager.GetString("Descriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptors.
        /// </summary>
        internal static string DescriptorsDesc {
            get {
                return ResourceManager.GetString("DescriptorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptorWeight.
        /// </summary>
        internal static string DescriptorWeightDesc {
            get {
                return ResourceManager.GetString("DescriptorWeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time(milliseconds) it will wait..
        /// </summary>
        internal static string DurationDesc {
            get {
                return ResourceManager.GetString("DurationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string EventDesc {
            get {
                return ResourceManager.GetString("EventDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitPolicy.
        /// </summary>
        internal static string ExitPolicy {
            get {
                return ResourceManager.GetString("ExitPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExitPolicy, to determine what to do when exiting.
        /// </summary>
        internal static string ExitPolicyDesc {
            get {
                return ResourceManager.GetString("ExitPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File Warning.
        /// </summary>
        internal static string ExportFileWarning {
            get {
                return ResourceManager.GetString("ExportFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailurePolicy.
        /// </summary>
        internal static string FailurePolicy {
            get {
                return ResourceManager.GetString("FailurePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the policy to return FAILURE.
        /// </summary>
        internal static string FailurePolicyDesc {
            get {
                return ResourceManager.GetString("FailurePolicyDesc", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap failureUntil_ico {
            get {
                object obj = ResourceManager.GetObject("failureUntil_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string FalseDesc {
            get {
                return ResourceManager.GetString("FalseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string Frames {
            get {
                return ResourceManager.GetString("Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames.
        /// </summary>
        internal static string FramesDesc {
            get {
                return ResourceManager.GetString("FramesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getter.
        /// </summary>
        internal static string Getter {
            get {
                return ResourceManager.GetString("Getter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gettter.
        /// </summary>
        internal static string GetterDesc {
            get {
                return ResourceManager.GetString("GetterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IfElse.
        /// </summary>
        internal static string IfElse {
            get {
                return ResourceManager.GetString("IfElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string IfElseCondition {
            get {
                return ResourceManager.GetString("IfElseCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if condition is true, the &apos;If&apos; is ticked, if condition is false, the &apos;Else&apos; is ticked.
        /// </summary>
        internal static string IfElseDesc {
            get {
                return ResourceManager.GetString("IfElseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Else.
        /// </summary>
        internal static string IfElseElse {
            get {
                return ResourceManager.GetString("IfElseElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If.
        /// </summary>
        internal static string IfElseIf {
            get {
                return ResourceManager.GetString("IfElseIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse.
        /// </summary>
        internal static string Impulse {
            get {
                return ResourceManager.GetString("Impulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node is only visible when one of the associated events were fired..
        /// </summary>
        internal static string ImpulseDesc {
            get {
                return ResourceManager.GetString("ImpulseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulse can only be children of Selector.
        /// </summary>
        internal static string ImpulseParentError {
            get {
                return ResourceManager.GetString("ImpulseParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no event.
        /// </summary>
        internal static string ImpulseWithoutEventError {
            get {
                return ResourceManager.GetString("ImpulseWithoutEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap method_icon {
            get {
                object obj = ResourceManager.GetObject("method_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string MethodAction {
            get {
                return ResourceManager.GetString("MethodAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods can only be Tasks&apos; sub nodes..
        /// </summary>
        internal static string MethodDesc {
            get {
                return ResourceManager.GetString("MethodDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effector.
        /// </summary>
        internal static string MethodEffector {
            get {
                return ResourceManager.GetString("MethodEffector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method can only be inserted to Task..
        /// </summary>
        internal static string MethodParentError {
            get {
                return ResourceManager.GetString("MethodParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition.
        /// </summary>
        internal static string MethodPrecondition {
            get {
                return ResourceManager.GetString("MethodPrecondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action branch is specified.
        /// </summary>
        internal static string NoActionError {
            get {
                return ResourceManager.GetString("NoActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string NodeGroupActions {
            get {
                return ResourceManager.GetString("NodeGroupActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string NodeGroupAttachments {
            get {
                return ResourceManager.GetString("NodeGroupAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string NodeGroupBranches {
            get {
                return ResourceManager.GetString("NodeGroupBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composites.
        /// </summary>
        internal static string NodeGroupComposites {
            get {
                return ResourceManager.GetString("NodeGroupComposites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string NodeGroupConditions {
            get {
                return ResourceManager.GetString("NodeGroupConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorators.
        /// </summary>
        internal static string NodeGroupDecorators {
            get {
                return ResourceManager.GetString("NodeGroupDecorators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string NodeGroupEvents {
            get {
                return ResourceManager.GetString("NodeGroupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulses.
        /// </summary>
        internal static string NodeGroupImpulses {
            get {
                return ResourceManager.GetString("NodeGroupImpulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves.
        /// </summary>
        internal static string NodeGroupLeaves {
            get {
                return ResourceManager.GetString("NodeGroupLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No effector branch is specified.
        /// </summary>
        internal static string NoEffectorError {
            get {
                return ResourceManager.GetString("NoEffectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noop.
        /// </summary>
        internal static string Noop {
            get {
                return ResourceManager.GetString("Noop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no operation.
        /// </summary>
        internal static string NoopDesc {
            get {
                return ResourceManager.GetString("NoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Precondition branch is specified.
        /// </summary>
        internal static string NoPreconditionError {
            get {
                return ResourceManager.GetString("NoPreconditionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand is not complete!.
        /// </summary>
        internal static string OperandError {
            get {
                return ResourceManager.GetString("OperandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand is not complete!.
        /// </summary>
        internal static string OperatandIsNotComplete {
            get {
                return ResourceManager.GetString("OperatandIsNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true if any one of the children is true.
        /// </summary>
        internal static string OrDesc {
            get {
                return ResourceManager.GetString("OrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel.
        /// </summary>
        internal static string Parallel {
            get {
                return ResourceManager.GetString("Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all the children are updated in parallel.
        /// </summary>
        internal static string ParallelDesc {
            get {
                return ResourceManager.GetString("ParallelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreAction.
        /// </summary>
        internal static string PreAction {
            get {
                return ResourceManager.GetString("PreAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to check a precondition before taking action.
        /// </summary>
        internal static string PreActionDesc {
            get {
                return ResourceManager.GetString("PreActionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate.
        /// </summary>
        internal static string Predicate {
            get {
                return ResourceManager.GetString("Predicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compare properties/pars with the right operand.
        /// </summary>
        internal static string PredicateDesc {
            get {
                return ResourceManager.GetString("PredicateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub trees are queried.
        /// </summary>
        internal static string QueryDesc {
            get {
                return ResourceManager.GetString("QueryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RandomGenerator.
        /// </summary>
        internal static string RandomGenerator {
            get {
                return ResourceManager.GetString("RandomGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can specify a method to return a &apos;int&apos; as the random number..
        /// </summary>
        internal static string RandomGeneratorDesc {
            get {
                return ResourceManager.GetString("RandomGeneratorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RandomGenerator is not specified， the default one is used!.
        /// </summary>
        internal static string RandomGeneratorNotSpecified {
            get {
                return ResourceManager.GetString("RandomGeneratorNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string ReferenceDesc {
            get {
                return ResourceManager.GetString("ReferenceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        internal static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node will call its attached nodes in the given order until one succeeds. If all attached nodes fail, this node fails, too..
        /// </summary>
        internal static string SelectorDesc {
            get {
                return ResourceManager.GetString("SelectorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectorLoop.
        /// </summary>
        internal static string SelectorLoop {
            get {
                return ResourceManager.GetString("SelectorLoop", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap selectorLoop_ico {
            get {
                object obj = ResourceManager.GetObject("selectorLoop_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children are not WithPrecondition.
        /// </summary>
        internal static string SelectorLoopChildChildError {
            get {
                return ResourceManager.GetString("SelectorLoopChildChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Selector, it keep selecting from the children nodes until one succeeds..
        /// </summary>
        internal static string SelectorLoopDesc {
            get {
                return ResourceManager.GetString("SelectorLoopDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectorProbability.
        /// </summary>
        internal static string SelectorProbability {
            get {
                return ResourceManager.GetString("SelectorProbability", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap selectorProbability_ico {
            get {
                object obj = ResourceManager.GetObject("selectorProbability_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector by probability.
        /// </summary>
        internal static string SelectorProbabilityDesc {
            get {
                return ResourceManager.GetString("SelectorProbabilityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectorStochastic.
        /// </summary>
        internal static string SelectorStochastic {
            get {
                return ResourceManager.GetString("SelectorStochastic", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap selectorStochastic_ico {
            get {
                object obj = ResourceManager.GetObject("selectorStochastic_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector Stochastic.
        /// </summary>
        internal static string SelectorStochasticDesc {
            get {
                return ResourceManager.GetString("SelectorStochasticDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node will call its attached nodes in the given order. If any of the attached nodes fails, this node fails as well..
        /// </summary>
        internal static string SequenceDesc {
            get {
                return ResourceManager.GetString("SequenceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceStochastic.
        /// </summary>
        internal static string SequenceStochastic {
            get {
                return ResourceManager.GetString("SequenceStochastic", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap sequenceStochastic_ico {
            get {
                object obj = ResourceManager.GetObject("sequenceStochastic_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Stochastic.
        /// </summary>
        internal static string SequenceStochasticDesc {
            get {
                return ResourceManager.GetString("SequenceStochasticDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuccessPolicy.
        /// </summary>
        internal static string SuccessPolicy {
            get {
                return ResourceManager.GetString("SuccessPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the policy to return SUCESS.
        /// </summary>
        internal static string SuccessPolicyDesc {
            get {
                return ResourceManager.GetString("SuccessPolicyDesc", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap successUntil_ico {
            get {
                object obj = ResourceManager.GetObject("successUntil_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap task_icon {
            get {
                object obj = ResourceManager.GetObject("task_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children are not Method.
        /// </summary>
        internal static string TaskChildChildError {
            get {
                return ResourceManager.GetString("TaskChildChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Task can be expanded into other tasks or actions on the runtime..
        /// </summary>
        internal static string TaskDesc {
            get {
                return ResourceManager.GetString("TaskDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string TrueDesc {
            get {
                return ResourceManager.GetString("TrueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the specified miliseconds.
        /// </summary>
        internal static string WaitDesc {
            get {
                return ResourceManager.GetString("WaitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitforSignal.
        /// </summary>
        internal static string WaitforSignal {
            get {
                return ResourceManager.GetString("WaitforSignal", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap waitforSignal_ico {
            get {
                object obj = ResourceManager.GetObject("waitforSignal_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blocked until the predicates are true.
        /// </summary>
        internal static string WaitforSignalDesc {
            get {
                return ResourceManager.GetString("WaitforSignalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitFrames.
        /// </summary>
        internal static string WaitFrames {
            get {
                return ResourceManager.GetString("WaitFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the specified frames.
        /// </summary>
        internal static string WaitFramesDesc {
            get {
                return ResourceManager.GetString("WaitFramesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string WeightDesc {
            get {
                return ResourceManager.GetString("WeightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its parent node is not SelectorProbability..
        /// </summary>
        internal static string WeightParentError {
            get {
                return ResourceManager.GetString("WeightParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithPrecondition.
        /// </summary>
        internal static string WithPrecondition {
            get {
                return ResourceManager.GetString("WithPrecondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string WithPreconditionAction {
            get {
                return ResourceManager.GetString("WithPreconditionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it has two branches:precondition and action. action branch can only be called if the precondition branch returns success..
        /// </summary>
        internal static string WithPreconditionDesc {
            get {
                return ResourceManager.GetString("WithPreconditionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithPrecondition can only be inserted to SelectorLoop..
        /// </summary>
        internal static string WithPreconditionParentError {
            get {
                return ResourceManager.GetString("WithPreconditionParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition.
        /// </summary>
        internal static string WithPreconditionPrecondition {
            get {
                return ResourceManager.GetString("WithPreconditionPrecondition", resourceCulture);
            }
        }
    }
}
