// the configured options generated by cmake
// please don't modify it manually unless you know what you are doing

/* #undef BEHAVIAC_RELEASE_CUSTOMIZED */

#ifdef BEHAVIAC_RELEASE_CUSTOMIZED
	#define BEHAVIAC_RELEASE 		0
#endif

#define BEHAVIAC_VERSION_STRING 	"3.3.16"

#define BEHAVIAC_ENABLE_LUA 		0
