// the configured options generated by cmake
// please don't modify it manually unless you know what you are doing

/* #undef BEHAVIAC_RELEASE_CUSTOMIZED */

#ifdef BEHAVIAC_RELEASE_CUSTOMIZED
#define BEHAVIAC_RELEASE 		0
#endif

