// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#include "behaviac/agent/registermacros.h"
#include "customizedtypes.h"

// -------------------
// Customized enums
// -------------------

BEHAVIAC_BEGIN_ENUM(ETest, ETest)
{
	BEHAVIAC_ENUMCLASS_DISPLAY_INFO(L"ETest", L"");

	BEHAVIAC_ENUM_ITEM(EA, "EA");

	BEHAVIAC_ENUM_ITEM(EB, "EB");

	BEHAVIAC_ENUM_ITEM(EC, "EC");
}
BEHAVIAC_END_ENUM()

// -------------------
// Customized structs
// -------------------

BEHAVIAC_BEGIN_PROPERTIES(StructTest)
{
	BEHAVIAC_CLASS_DISPLAYNAME(L"StructTest");
	BEHAVIAC_CLASS_DESC(L"");

	BEHAVIAC_REGISTER_PROPERTY(a).DISPLAYNAME(L"a").DESC(L"a");
}
BEHAVIAC_END_PROPERTIES()
