// ---------------------------------------------------------------------
// This file is auto-generated by behaviac designer, so please don't modify it by yourself!
// ---------------------------------------------------------------------

#pragma once
#include "behaviac/agent/agent.h"
#include "behaviac/agent/taskmethod.h"
#include "behaviac/property/typeregister.h"

namespace behaviac
{
	class CppBehaviorLoaderImplement : CppBehaviorLoader
	{
	public:
		CppBehaviorLoaderImplement()
		{
			AgentProperties::SetInstance(this);
		}

		virtual ~CppBehaviorLoaderImplement()
		{
		}

		virtual bool load()
		{
			// ---------------------------------------------------------------------
			// properties
			// ---------------------------------------------------------------------

			AgentProperties* bb = NULL;

			// CBTPlayer
			bb = BEHAVIAC_NEW AgentProperties("CBTPlayer");
			AgentProperties::SetAgentTypeBlackboards("CBTPlayer", bb);
			bb->AddProperty("uint", false, "m_iBaseSpeed", "0", "CBTPlayer");

			// ---------------------------------------------------------------------
			// tasks
			// ---------------------------------------------------------------------

			CTagObjectDescriptor* objectDesc = NULL;
			CCustomMethod* customeMethod = NULL;

			return true;
		}

		virtual void RegisterCustomizedTypes_()
		{
		}

		virtual void UnRegisterCustomizedTypes_()
		{
		}
	};

	static CppBehaviorLoaderImplement cppBehaviorLoaderImplement;
}
